FROM php:8.2-fpm-bullseye

RUN apt-get update && apt-get install -y \
    gnupg2 unixodbc unixodbc-dev curl apt-transport-https \
    software-properties-common libgssapi-krb5-2 \
    git zip unzip \
    libfreetype6-dev libjpeg62-turbo-dev libpng-dev \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18 \
    && echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc \
    && pecl install sqlsrv pdo_sqlsrv \
    && docker-php-ext-enable sqlsrv pdo_sqlsrv \
    # Install GD with FreeType and JPEG support for image processing /needed for Captcha
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    # Composer
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && apt-get clean && rm -rf /var/lib/apt/lists/* \
    # Install procps for process monitoring
    && apt-get update && apt-get install -y procps

# Copy init script
COPY init.sh /usr/local/bin/init.sh
RUN chmod +x /usr/local/bin/init.sh

WORKDIR /var/www/html

# Set permissions needed for Gii code generator and general web server usage
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 775 /var/www/html \
    && find /var/www/html -type f -exec chmod 664 {} +
